### ISSUE TITLE
建议顺便搞一个Vue3的版本

### ISSUE THREAD

**Issue by langren1353** [ruofee/vue-ellipsis-component#10]
如题，逐渐的会有越来越多的人使用Vue3
可以尝试从最开始干别人还没干的事

很好的库，希望持续迭代

ps：支持后可以在文档中写上支持Vue2、Vue3

**Comment by ruofee** [comment]
感谢你的建议，有空的话 vue3 版本会在近期进行开发，感谢支持 Thanks♪(･ω･)ﾉ

**Comment by ruofee** [comment]
支持 vue 3.x 的版本：https://github.com/ruofee/vue-ellipsis-3
