### ISSUE TITLE
使用onReflow并设置字体大小，文字全部被省略了

### ISSUE THREAD

**Issue by zkqmylove** [ruofee/vue-ellipsis-component#11]
当我设置字体大小，并使用 onReflow 时，会出现文字全部被省略，而不是溢出部分显示为...
查看了一下代码发现，`truncateText`函数中有一个比较:

`const isExceededMaximun = height > max;`

这里的height通过`getElementHeight`方法获得，得到的结果比max大，从而导致文字部分都没有了。

误差大约是：0 < height - max < 0.00001 
这可能是float精度的问题引起

**Comment by ruofee** [comment]
感谢你提出这个 issue，可以麻烦补充一个简单的例子吗，我本地跑一下试试

**Comment by zkqmylove** [comment]
额，有点小尴尬
经过我的几次实验发现这个问题只出现在我的笔记本的浏览器上，而台式机没有这个问题
代码跑在台式机上，浏览器都是Edge（版本：107.0.1418.56）

代码非常简单，就是一个div包裹了vue-ellipsis，然后div设置了宽度300，字体及背景

笔记本的浏览器在不同的缩放下出现的结果不一样：
（这里第一行是vue-ellipsis，第二行不是）

![1](https://user-images.githubusercontent.com/40973224/204267238-880bfe9b-dd8d-42d7-a356-74111a7da146.png)

![2](https://user-images.githubusercontent.com/40973224/204267284-c9545002-2ebc-4320-addc-3f45e10d957e.png)

**Comment by zkqmylove** [comment]
> 感谢你提出这个 issue，可以麻烦补充一个简单的例子吗，我本地跑一下试试

下面是断点调试的情况，当出现height=120时显示正常，但是在不断的对浏览器放大缩小的操作时，会出现height不为整数的情况，如果height > 120 就出现了显示异常（第三张图）。

这个图显示的情况是正常时的样子，第一次height计算出来为120，每次减少30
![4](https://user-images.githubusercontent.com/40973224/204273483-2f8783ff-634c-41f6-be47-a121eb077639.png)

这个图显示的情况也是正常的，但是height的值已经是小于120了
![3](https://user-images.githubusercontent.com/40973224/204273831-2f4ef5cf-5bd1-430d-aae9-06051bbbe810.png)

这个图显示的情况是异常的，height值大于120
![5](https://user-images.githubusercontent.com/40973224/204273927-e2779f52-21c8-46c7-87ca-6c0bca34f0f2.png)

**Comment by ruofee** [comment]
先确认两个事情：
1. 你设置到 vue-ellipsis-component 的 props 是 `visibleHeight ` 还是 `visibleLine` 呢？
2. 文本有没有默认设置 `line-height`？

如果可以，最好是把你使用 vue-ellipsis-component 的代码完整地贴上来！

很抱歉 😂 我身边没有 windows 系统的电脑，但从你的描述来看，如果在浏览器缩放的情况，`getElementHeight` 获取到的高度会发生浮动，这像是个浏览器的问题，因为 `getElementHeight` 是直接使用原生的 api，没做其他特殊处理：

```ts
export function getElementHeight(element: HTMLElement): number {
  return element.getBoundingClientRect().height;
}
```

**Comment by zkqmylove** [comment]
> 
这个很不好复现，我测试了很多次，并且在我的台式机上也出现了，但是只在特定的缩放大小下容易产生，我的显示器是2k的在缩放比例175%时容易触发。

感觉可以在 truncateText 这个方法中对 height 四舍五入取整，或者给max增加一个0.01的值

代码如下：
``` javascript
<template>
  <div class="wrapper">
    <vue-ellipsis
      :text="msg"
      :onReflow="onReflow"
    />
  </div>
</template>

<script>
import { VueEllipsis } from 'vue-ellipsis-component';

export default {
  name: 'HelloWorld2',
  components: { VueEllipsis },
  data() {
    return {
      msg: 'hh哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈hh哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈hh哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈hh哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈hh哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈'
    };
  },
  methods: {
    onReflow(ellipsis, text) {
      console.log('xxxxxx', ellipsis, text);
    }
  }
};
</script>

<style lang="less" scoped>
.wrapper {
  width: 300px;
  font-size: 14px;
  line-height: 14px;
  background-color: #eee;
}</style>

```

``` javascript
<template>
  <div id="app">
    <HelloWorld2/>
  </div>
</template>

<script>
import HelloWorld2 from './components/HelloWorld2.vue'

export default {
  name: 'App',
  components: {
    HelloWorld2
  }
}
</script>


```

**Comment by zkqmylove** [comment]
由于比较难以复现，我这里将我出现的情况，及我断点调试的步骤截图发出来以供参考

这里是第一次进入
![1](https://user-images.githubusercontent.com/40973224/204297643-89edd483-dc6a-43aa-9ddb-71fbc15b497a.png)

第二次，此时已经变成两行了
![2](https://user-images.githubusercontent.com/40973224/204297729-b8a39670-5433-4b71-bb77-3abbf38cf2b5.png)

第三次，此时为一行
![3](https://user-images.githubusercontent.com/40973224/204297859-873f77d3-c931-4943-a1cd-28ec57037581.png)

随后的几步都是在这一行内进行缩减，这里贴出最后一位时的情况
![5](https://user-images.githubusercontent.com/40973224/204298058-66856945-89f9-48c8-abfb-417c7d9db823.png)

**Comment by ruofee** [comment]
感谢，我在 chrome 上已经可以复现了，在一定的缩放条件下 `getBoundingClientRect` 获取的高度确实是浮点数（不精确的！）。我先去看看导致这个问题的原因以及解决方法！

**Comment by zkqmylove** [comment]
> 感谢，我在 chrome 上已经可以复现了，在一定的缩放条件下 `getBoundingClientRect` 获取的高度确实是浮点数（不精确的！）。我先去看看导致这个问题的原因以及解决方法！

还得感谢您的无私分享😊

**Comment by ruofee** [comment]
我先用 `clientHeight` 替代了 `getBoundingClientRect().height`，已经发了新版本 v1.0.4，你可以重新升级看看。

**Comment by zkqmylove** [comment]
> 我先用 `clientHeight` 替代了 `getBoundingClientRect().height`，已经发了新版本 v1.0.4，你可以重新升级看看。

我这边测试`v1.0.4`已经没问题了👍
