### ISSUE TITLE
建议增加对br和\n的处理

### ISSUE THREAD

**Issue by Panjun-520** [ruofee/vue-ellipsis-component#13]
您好，在使用组件进行富文本渲染时，当文本里有<br>或者\n时，我想让他任意行显示，但省略号会占一行，
![image](https://github.com/ruofee/vue-ellipsis-component/assets/114401109/f1bfd258-0343-444f-9217-8ca47ca17e0e)

**Comment by ruofee** [comment]
你的意思是不想在 `<br>` 这一行缩略吗？而是在图中的圆圈处缩略？
<img width="723" alt="image" src="https://github.com/ruofee/vue-ellipsis-component/assets/19842213/acd8cfd1-c972-47d3-90e6-44f33e656387">

**Comment by Panjun-520** [comment]
对，而且富文本里\n渲染和< br >渲染不一样，都是换行，有的\n还没有渲染出来
![image](https://github.com/ruofee/vue-ellipsis-component/assets/114401109/e7a9faf8-13d8-4d24-8f90-73220f6013ac)

**Comment by ruofee** [comment]
可以贴一下你的富文本内容吗？并且提供一下 `vue-ellipsis-component` 的 `props`。

另外，富文本中的 `\n` 是不会执行成换行的 😂，只有 `<br>` 会转换成换行，你可以自行使用 `innerHTML` 尝试一下。

**Comment by Panjun-520** [comment]
可以，这是有br的"💝 💝 Log in daily for valuable rewards!<br /> ✅An Exciting Adventure and a Rich Gameplay<br /> 💎 Pack code: 🎁VIP555 🎁VIP777 🎁VIP999"
这是由\n的"
"APPLICATIONS CLOSING SOON.\n\nThe Visual Artists Association offers an exclusive Mentorship Programme that’s carefully curated to provide you with the tools to sell more art.  \n\nWe offer professional expertise on all aspects of your Art Career, including: Career Coaching, Critical Feedback, Marketing Insights. \nLimited Spaces Available."
![image](https://github.com/ruofee/vue-ellipsis-component/assets/114401109/0843ae60-6340-4771-89b6-213b9103991e)

![image](https://github.com/ruofee/vue-ellipsis-component/assets/114401109/05d00d96-9d0a-4971-8f8e-e475ef5cab94)

**Comment by ruofee** [comment]
看起来是存在 bug 导致的，我这两天会抽空解决一下 😂

**Comment by Panjun-520** [comment]
好嘞👍

**Comment by ruofee** [comment]
@Panjun-520 已经解决这个问题了，可以尝试安装 1.0.7 版本
不好意思 😂 三周了才帮你解决这个 bug

**Comment by Panjun-520** [comment]
感谢，我下了1.0.8
