### ISSUE TITLE
text  是动态时无法渲染文本

### ISSUE THREAD

**Issue by canyuegongzi** [ruofee/vue-ellipsis-component#14]
```
<VueEllipsis :visible-line="1" use-inner-html :text="getAttrStr">
            <template v-slot:ellipsisNode>
              <span style="font-size: 12px; color: red">展开</span>
            </template>
          </VueEllipsis>
```

<img width="653" alt="image" src="https://github.com/ruofee/vue-ellipsis-component/assets/32031360/42055dba-0825-4d84-b5ce-bdf155bc131c">

<img width="262" alt="image" src="https://github.com/ruofee/vue-ellipsis-component/assets/32031360/316c70f5-27ec-4912-aa8d-cf78a0a2ea53">

**Comment by ruofee** [comment]
`getAttrStr` 是计算属性（computed）还是方法（method）呢？

**Comment by ruofee** [comment]
> `getAttrStr` 是计算属性（computed）还是方法（method）呢？

如果是 method 的话，我理解应该是语法使用上的问题，你应该执行这个函数：

```html
<vue-ellipsis-component :text="getAttrStr()">
</vue-ellipsis-component>
```

如上面的代码，应该是 `:text="getAttrStr()"`，而不是 `:text="getAttrStr"`

**Comment by canyuegongzi** [comment]
> computed

computed

**Comment by canyuegongzi** [comment]
> > `getAttrStr` 是计算属性（computed）还是方法（method）呢？
> 
> 如果是 method 的话，我理解应该是语法使用上的问题，你应该执行这个函数：
> 
> ```
> <vue-ellipsis-component :text="getAttrStr()">
> </vue-ellipsis-component>
> ```
> 
> 如上面的代码，应该是 `:text="getAttrStr()"`，而不是 `:text="getAttrStr"`

computed

**Comment by canyuegongzi** [comment]
> > `getAttrStr` 是计算属性（computed）还是方法（method）呢？
> 
> 如果是 method 的话，我理解应该是语法使用上的问题，你应该执行这个函数：
> 
> ```
> <vue-ellipsis-component :text="getAttrStr()">
> </vue-ellipsis-component>
> ```
> 
> 如上面的代码，应该是 `:text="getAttrStr()"`，而不是 `:text="getAttrStr"`

暂时手动实现了个组件，有空了再研究研究啥原因造成的

**Comment by ruofee** [comment]
😂 我本地试了一下，暂时不能复现你说到的问题

**Comment by ruofee** [comment]
> 😂 我本地试了一下，暂时不能复现你说到的问题

你有空了可以补充一下例子，issue 先关闭了~
