### ISSUE TITLE
您好，这个有react版本吗？

### ISSUE THREAD

**Issue by Panjun-520** [ruofee/vue-ellipsis-component#16]

**Comment by ruofee** [comment]
https://github.com/chenquincy/react-ellipsis

**Comment by Panjun-520** [comment]
![06FEDE38](https://github.com/user-attachments/assets/6208ed0f-2c31-4548-a40b-2c481d310cea)
厉害

**Comment by Panjun-520** [comment]
这个跟那个vue版有相同的问题
![image](https://github.com/user-attachments/assets/537b7170-d6b8-4fec-a4a8-efca69434621)
我希望在第二行或者在指定行高的地方显示省略号，这里收到br的影响导致换行了，可以解决下吗

**Comment by ruofee** [comment]
嗯嗯，我修复一下，下次可以去对应仓库提 issue @Panjun-520

**Comment by Panjun-520** [comment]
好的，
![0B239196](https://github.com/user-attachments/assets/0999fb50-b9cf-403d-b4e6-43c847f9e136)

**Comment by ruofee** [comment]
@Panjun-520 作者已经发布新版本了，试着安装最新版本试试：1.1.11
